// ColorCodedQASM Mock Data
import type {
  Artifact,
  Collection,
  Artisan,
  ProtocolStep,
  JournalPost,
  Testimonial,
  NavLink,
} from "./qasm-types";

export const navLinks: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "Archive", href: "/archive" },
  { label: "Encode", href: "/encode" },
  { label: "Artisans", href: "/artisans" },
  { label: "About", href: "/about" },
];

export const artifacts: Artifact[] = [
  {
    id: "1",
    title: "Dilkash Kimono Jacket",
    slug: "dilkash-kimono-jacket",
    collection: "Threads of Abundance",
    collectionSlug: "threads-of-abundance",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    availability: "in_stock",
    description: "Hand-embroidered kimono jacket featuring Mughal-inspired floral motifs. Each piece requires 120+ hours of artisan work.",
    materials: ["Organic cotton", "Silk thread", "Gold zari"],
    techniques: ["Aari embroidery", "Zardozi"],
    artisan: "Master Rafiq",
    leadTime: "6-8 weeks",
    featured: true,
  },
  {
    id: "2",
    title: "Hand Embroidered Oversized Suit",
    slug: "hand-embroidered-oversized-suit",
    collection: "Threads of Abundance",
    collectionSlug: "threads-of-abundance",
    price: 1590,
    images: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L"],
    availability: "in_stock",
    description: "Oversized silhouette with intricate hand embroidery covering the entire surface. A wearable archive of textile heritage.",
    materials: ["Wool blend", "Silk embroidery thread"],
    techniques: ["Resham work", "Chain stitch"],
    artisan: "Collective",
    leadTime: "8-10 weeks",
    featured: true,
  },
  {
    id: "3",
    title: "Jamdani Draped Dress",
    slug: "jamdani-draped-dress",
    collection: "Jamdani Capsule",
    collectionSlug: "jamdani-capsule",
    price: 1720,
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1200&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    availability: "pre_order",
    description: "Sculptural draped dress in heritage Jamdani weave. Each meter of fabric takes a weaver three days to complete.",
    materials: ["Jamdani cotton", "Handwoven"],
    techniques: ["Jamdani weaving"],
    artisan: "Weavers of Tangail",
    leadTime: "10-12 weeks",
    featured: true,
  },
  {
    id: "4",
    title: "Gyre Falcon Corduroy Plaid Suit",
    slug: "gyre-falcon-corduroy-suit",
    collection: "Threads of Abundance",
    collectionSlug: "threads-of-abundance",
    price: 1300,
    images: ["https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    availability: "in_stock",
    description: "Cotton plaid and green corduroy, oversized notch lapel. Nature-inspired embroidery depicting the gyre falcon.",
    materials: ["Cotton plaid", "Corduroy", "Wool"],
    techniques: ["Hand embroidery", "Tailoring"],
    artisan: "Master Hussain",
    featured: true,
  },
  {
    id: "5",
    title: "Blue Iris Plant and Bird Shacket",
    slug: "blue-iris-shacket",
    collection: "Threads of Abundance",
    collectionSlug: "threads-of-abundance",
    price: 400,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L"],
    availability: "in_stock",
    description: "Lightweight shirt-jacket hybrid with botanical and avian motifs. Cotton and tropical fabric blend.",
    materials: ["Organic cotton", "Tropical blend"],
    techniques: ["Block printing", "Hand finishing"],
    artisan: "Studio Collective",
  },
  {
    id: "6",
    title: "Brick Lotus Set",
    slug: "brick-lotus-set",
    collection: "Lotus Collection",
    collectionSlug: "lotus-collection",
    price: 666,
    images: ["https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&h=1200&fit=crop"],
    sizes: ["XS", "S", "M", "L"],
    availability: "in_stock",
    description: "Coordinated set featuring the sacred lotus in terracotta tones. Each petal rendered in fine embroidery.",
    materials: ["Cotton", "Silk thread"],
    techniques: ["Aari embroidery"],
    artisan: "Artisan Collective",
  },
  {
    id: "7",
    title: "Egyptian Lotus Ice Blue Vest",
    slug: "egyptian-lotus-vest",
    collection: "Lotus Collection",
    collectionSlug: "lotus-collection",
    price: 444,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L"],
    availability: "in_stock",
    description: "Ice blue vest adorned with Egyptian lotus motifs. A bridge between ancient civilizations through textile.",
    materials: ["Linen", "Cotton"],
    techniques: ["Hand embroidery"],
    artisan: "Master Amina",
  },
  {
    id: "8",
    title: "Imaginary Birds Wool Pants",
    slug: "imaginary-birds-pants",
    collection: "Threads of Abundance",
    collectionSlug: "threads-of-abundance",
    price: 460,
    compareAtPrice: 520,
    images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&h=1200&fit=crop"],
    sizes: ["S", "M", "L", "XL"],
    availability: "sold_out",
    description: "Wide straight leg pants with fantastical bird embroidery. Unisex fit with elasticated waist.",
    materials: ["Wool", "Cotton lining"],
    techniques: ["Free-hand embroidery"],
    artisan: "Master Rafiq",
  },
];

export const collections: Collection[] = [
  {
    id: "1",
    title: "Threads of Abundance",
    slug: "threads-of-abundance",
    tagline: "Nature rendered in thread",
    description: "A collection celebrating the abundant natural world through intricate embroidery. Each piece features flora and fauna motifs executed with meticulous hand stitching.",
    heroImage: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1600&h=900&fit=crop",
    heroVideo: "/videos/threads-hero.mp4",
    artifacts: artifacts.filter(a => a.collectionSlug === "threads-of-abundance"),
  },
  {
    id: "2",
    title: "Jamdani Capsule",
    slug: "jamdani-capsule",
    tagline: "Heritage woven anew",
    description: "Reviving the endangered art of Jamdani weaving from Bengal. Each piece supports traditional weavers keeping this 2000-year-old craft alive.",
    heroImage: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=1600&h=900&fit=crop",
    artifacts: artifacts.filter(a => a.collectionSlug === "jamdani-capsule"),
  },
  {
    id: "3",
    title: "Lotus Collection",
    slug: "lotus-collection",
    tagline: "Sacred geometry in silk",
    description: "The lotus appears across South Asian traditions as a symbol of purity and enlightenment. This collection traces its journey through textile.",
    heroImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&h=900&fit=crop",
    artifacts: artifacts.filter(a => a.collectionSlug === "lotus-collection"),
  },
];

export const artisans: Artisan[] = [
  {
    id: "1",
    name: "Master Rafiq Ahmed",
    craft: "Aari Embroidery",
    region: "Kashmir, India",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop",
    bio: "Third-generation embroiderer from Srinagar. Master Rafiq has dedicated 40 years to preserving and evolving the Kashmiri Aari technique.",
    quote: "Every stitch is a prayer. Every pattern, a poem written by my ancestors.",
    techniques: ["Aari", "Sozni", "Tilla"],
    yearsOfExperience: 40,
  },
  {
    id: "2",
    name: "Amina Begum",
    craft: "Zardozi Work",
    region: "Lucknow, India",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&h=1000&fit=crop",
    bio: "One of the few female masters of Zardozi, the gold embroidery technique once reserved for Mughal royalty.",
    quote: "I am teaching my daughters. The thread must not break.",
    techniques: ["Zardozi", "Kamdani", "Dabka"],
    yearsOfExperience: 35,
  },
  {
    id: "3",
    name: "Abdul Karim",
    craft: "Jamdani Weaving",
    region: "Tangail, Bangladesh",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop",
    bio: "Master weaver whose family has practiced Jamdani for seven generations. UNESCO recognized this tradition as Intangible Cultural Heritage.",
    quote: "The loom speaks. I only listen and follow.",
    techniques: ["Jamdani", "Muslin"],
    yearsOfExperience: 45,
  },
  {
    id: "4",
    name: "Hussain Ali",
    craft: "Block Printing",
    region: "Jaipur, India",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=1000&fit=crop",
    bio: "Fourth-generation block printer using hand-carved teak blocks and natural dyes passed down through his family.",
    quote: "Each block carries the fingerprints of my grandfather.",
    techniques: ["Block printing", "Natural dyeing"],
    yearsOfExperience: 30,
  },
];

export const protocolSteps: ProtocolStep[] = [
  {
    number: 1,
    icon: "https://api.iconify.design/ph:eye-light.svg",
    title: "Share Your Vision",
    description: "Begin the encoding process. Share inspiration, preferences, and the story you want your artifact to tell.",
    days: "Day 1",
  },
  {
    number: 2,
    icon: "https://api.iconify.design/ph:pencil-line-light.svg",
    title: "Design & Iteration",
    description: "Our designers translate your vision into sketches and patterns. Review, refine, and approve the blueprint.",
    days: "Days 2-7",
  },
  {
    number: 3,
    icon: "https://api.iconify.design/ph:swatches-light.svg",
    title: "Material Selection",
    description: "Choose from our library of ethically sourced fabrics. Each material has its own story and origin.",
    days: "Days 8-12",
  },
  {
    number: 4,
    icon: "https://api.iconify.design/ph:scissors-light.svg",
    title: "Artisan Crafting",
    description: "Master artisans bring your design to life using techniques passed down through generations.",
    days: "Days 13-38",
  },
  {
    number: 5,
    icon: "https://api.iconify.design/ph:package-light.svg",
    title: "Artifact Delivery",
    description: "Your finished piece, along with documentation of its creation journey, arrives at your doorstep.",
    days: "Days 39-44",
  },
];

export const journalPosts: JournalPost[] = [
  {
    id: "1",
    title: "The Last Jamdani Weavers of Tangail",
    slug: "last-jamdani-weavers",
    excerpt: "Inside the workshops where an ancient art form fights for survival in the modern world.",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&h=500&fit=crop",
    category: "Heritage",
    publishedAt: "2024-11-15",
    readTime: "8 min",
  },
  {
    id: "2",
    title: "Why Slow Fashion Isn't Slow Enough",
    slug: "slow-fashion-not-enough",
    excerpt: "The case for garments that take months to create and decades to appreciate.",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=500&fit=crop",
    category: "Philosophy",
    publishedAt: "2024-10-28",
    readTime: "5 min",
  },
  {
    id: "3",
    title: "Decoding Mughal Embroidery Patterns",
    slug: "decoding-mughal-patterns",
    excerpt: "The symbolic language hidden in every curve and flourish of traditional embroidery.",
    image: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&h=500&fit=crop",
    category: "Craft",
    publishedAt: "2024-10-10",
    readTime: "6 min",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Chen",
    location: "San Francisco, CA",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop",
    quote: "I didn't just receive a jacket—I received a piece of living history. The craftsmanship is beyond anything I've ever owned.",
    artifact: "Dilkash Kimono Jacket",
  },
  {
    id: "2",
    name: "Marcus Williams",
    location: "London, UK",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    quote: "The co-creation process felt like a collaboration across continents. I learned so much about the artisans making my suit.",
    artifact: "Hand Embroidered Oversized Suit",
  },
  {
    id: "3",
    name: "Priya Sharma",
    location: "Mumbai, India",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop",
    quote: "To wear Jamdani is to wear my grandmother's memories. ColorCodedQASM understood that perfectly.",
    artifact: "Jamdani Draped Dress",
  },
];

export const featuredArtifacts = artifacts.filter(a => a.featured);
